<?php

namespace Javaabu\MobileVerification\Support\Enums;

enum Countries: string
{
    case Afghanistan = 'AF';
    case Albania = 'AL';
    case Algeria = 'DZ';
    case AmericanSamoa = 'AS';
    case Andorra = 'AD';
    case Angola = 'AO';
    case Anguilla = 'AI';
    case Antarctica = 'AQ';
    case AntiguaAndBarbuda = 'AG';
    case Argentina = 'AR';
    case Armenia = 'AM';
    case Aruba = 'AW';
    case Australia = 'AU';
    case Austria = 'AT';
    case Azerbaijan = 'AZ';
    case Bahamas = 'BS';
    case Bahrain = 'BH';
    case Bangladesh = 'BD';
    case Barbados = 'BB';
    case Belarus = 'BY';
    case Belgium = 'BE';
    case Belize = 'BZ';
    case Benin = 'BJ';
    case Bermuda = 'BM';
    case Bhutan = 'BT';
    case Bolivia = 'BO';
    case BosniaAndHerzegovina = 'BA';
    case Botswana = 'BW';
    case Brazil = 'BR';
    case BritishIndianOceanTerritory = 'IO';
    case BritishVirginIslands = 'VG';
    case Brunei = 'BN';
    case Bulgaria = 'BG';
    case BurkinaFaso = 'BF';
    case Myanmar = 'MM';
    case Burundi = 'BI';
    case Cambodia = 'KH';
    case Cameroon = 'CM';
    case Canada = 'CA';
    case CapeVerde = 'CV';
    case CaymanIslands = 'KY';
    case CentralAfricanRepublic = 'CF';
    case Chad = 'TD';
    case Chile = 'CL';
    case China = 'CN';
    case ChristmasIsland = 'CX';
    case CocosIslands = 'CC';
    case Colombia = 'CO';
    case Comoros = 'KM';
    case RepublicOfTheCongo = 'CG';
    case DemocraticRepublicOfTheCongo = 'CD';
    case CookIslands = 'CK';
    case CostaRica = 'CR';
    case Croatia = 'HR';
    case Cuba = 'CU';
    case Curacao = 'CW';
    case Cyprus = 'CY';
    case CzechRepublic = 'CZ';
    case Denmark = 'DK';
    case Djibouti = 'DJ';
    case Dominica = 'DM';
    case DominicanRepublic = 'DO';
    case EastTimor = 'TL';
    case Ecuador = 'EC';
    case Egypt = 'EG';
    case ElSalvador = 'SV';
    case EquatorialGuinea = 'GQ';
    case Eritrea = 'ER';
    case Estonia = 'EE';
    case Ethiopia = 'ET';
    case FalklandIslands = 'FK';
    case FaroeIslands = 'FO';
    case Fiji = 'FJ';
    case Finland = 'FI';
    case France = 'FR';
    case FrenchPolynesia = 'PF';
    case Gabon = 'GA';
    case Gambia = 'GM';
    case Georgia = 'GE';
    case Germany = 'DE';
    case Ghana = 'GH';
    case Gibraltar = 'GI';
    case Greece = 'GR';
    case Greenland = 'GL';
    case Grenada = 'GD';
    case Guam = 'GU';
    case Guatemala = 'GT';
    case Guernsey = 'GG';
    case Guinea = 'GN';
    case GuineaBissau = 'GW';
    case Guyana = 'GY';
    case Haiti = 'HT';
    case Honduras = 'HN';
    case HongKong = 'HK';
    case Hungary = 'HU';
    case Iceland = 'IS';
    case India = 'IN';
    case Indonesia = 'ID';
    case Iran = 'IR';
    case Iraq = 'IQ';
    case Ireland = 'IE';
    case IsleOfMan = 'IM';
    case Israel = 'IL';
    case Italy = 'IT';
    case IvoryCoast = 'CI';
    case Jamaica = 'JM';
    case Japan = 'JP';
    case Jersey = 'JE';
    case Jordan = 'JO';
    case Kazakhstan = 'KZ';
    case Kenya = 'KE';
    case Kiribati = 'KI';
    case Kosovo = 'XK';
    case Kuwait = 'KW';
    case Kyrgyzstan = 'KG';
    case Laos = 'LA';
    case Latvia = 'LV';
    case Lebanon = 'LB';
    case Lesotho = 'LS';
    case Liberia = 'LR';
    case Libya = 'LY';
    case Liechtenstein = 'LI';
    case Lithuania = 'LT';
    case Luxembourg = 'LU';
    case Macau = 'MO';
    case Macedonia = 'MK';
    case Madagascar = 'MG';
    case Malawi = 'MW';
    case Malaysia = 'MY';
    case Maldives = 'MV';
    case Mali = 'ML';
    case Malta = 'MT';
    case MarshallIslands = 'MH';
    case Mauritania = 'MR';
    case Mauritius = 'MU';
    case Mayotte = 'YT';
    case Mexico = 'MX';
    case Micronesia = 'FM';
    case Moldova = 'MD';
    case Monaco = 'MC';
    case Mongolia = 'MN';
    case Montenegro = 'ME';
    case Montserrat = 'MS';
    case Morocco = 'MA';
    case Mozambique = 'MZ';
    case Namibia = 'NA';
    case Nauru = 'NR';
    case Nepal = 'NP';
    case Netherlands = 'NL';
    case NetherlandsAntilles = 'AN';
    case NewCaledonia = 'NC';
    case NewZealand = 'NZ';
    case Nicaragua = 'NI';
    case Niger = 'NE';
    case Nigeria = 'NG';
    case Niue = 'NU';
    case NorthernMarianaIslands = 'MP';
    case NorthKorea = 'KP';
    case Norway = 'NO';
    case Oman = 'OM';
    case Pakistan = 'PK';
    case Palau = 'PW';
    case Palestine = 'PS';
    case Panama = 'PA';
    case PapuaNewGuinea = 'PG';
    case Paraguay = 'PY';
    case Peru = 'PE';
    case Philippines = 'PH';
    case Pitcairn = 'PN';
    case Poland = 'PL';
    case Portugal = 'PT';
    case PuertoRico = 'PR';
    case Qatar = 'QA';
    case Reunion = 'RE';
    case Romania = 'RO';
    case Russia = 'RU';
    case Rwanda = 'RW';
    case SaintBarthelemy = 'BL';
    case Samoa = 'WS';
    case SanMarino = 'SM';
    case SaoTomeAndPrincipe = 'ST';
    case SaudiArabia = 'SA';
    case Senegal = 'SN';
    case Serbia = 'RS';
    case Seychelles = 'SC';
    case SierraLeone = 'SL';
    case Singapore = 'SG';
    case SintMaarten = 'SX';
    case Slovakia = 'SK';
    case Slovenia = 'SI';
    case SolomonIslands = 'SB';
    case Somalia = 'SO';
    case SouthAfrica = 'ZA';
    case SouthKorea = 'KR';
    case SouthSudan = 'SS';
    case Spain = 'ES';
    case SriLanka = 'LK';
    case SaintHelena = 'SH';
    case SaintKittsAndNevis = 'KN';
    case SaintLucia = 'LC';
    case SaintMartin = 'MF';
    case SaintPierreAndMiquelon = 'PM';
    case SaintVincentAndTheGrenadines = 'VC';
    case Sudan = 'SD';
    case Suriname = 'SR';
    case SvalbardAndJanMayen = 'SJ';
    case Swaziland = 'SZ';
    case Sweden = 'SE';
    case Switzerland = 'CH';
    case Syria = 'SY';
    case Taiwan = 'TW';
    case Tajikistan = 'TJ';
    case Tanzania = 'TZ';
    case Thailand = 'TH';
    case Togo = 'TG';
    case Tokelau = 'TK';
    case Tonga = 'TO';
    case TrinidadAndTobago = 'TT';
    case Tunisia = 'TN';
    case Turkey = 'TR';
    case Turkmenistan = 'TM';
    case TurksAndCaicosIslands = 'TC';
    case Tuvalu = 'TV';
    case UnitedArabEmirates = 'AE';
    case Uganda = 'UG';
    case UnitedKingdom = 'GB';
    case Ukraine = 'UA';
    case Uruguay = 'UY';
    case UnitedStates = 'US';
    case Uzbekistan = 'UZ';
    case Vanuatu = 'VU';
    case Vatican = 'VA';
    case Venezuela = 'VE';
    case Vietnam = 'VN';
    case USVirginIslands = 'VI';
    case WallisAndFutuna = 'WF';
    case WesternSahara = 'EH';
    case Yemen = 'YE';
    case Zambia = 'ZM';
    case Zimbabwe = 'ZW';


    public static function labels(): array
    {
        return [
            self::Afghanistan->value                  => __('Afghanistan'),
            self::Albania->value                      => __('Albania'),
            self::Algeria->value                      => __('Algeria'),
            self::AmericanSamoa->value                => __('American Samoa'),
            self::Andorra->value                      => __('Andorra'),
            self::Angola->value                       => __('Angola'),
            self::Anguilla->value                     => __('Anguilla'),
            self::Antarctica->value                   => __('Antarctica'),
            self::AntiguaAndBarbuda->value            => __('Antigua and Barbuda'),
            self::Argentina->value                    => __('Argentina'),
            self::Armenia->value                      => __('Armenia'),
            self::Aruba->value                        => __('Aruba'),
            self::Australia->value                    => __('Australia'),
            self::Austria->value                      => __('Austria'),
            self::Azerbaijan->value                   => __('Azerbaijan'),
            self::Bahamas->value                      => __('Bahamas'),
            self::Bahrain->value                      => __('Bahrain'),
            self::Bangladesh->value                   => __('Bangladesh'),
            self::Barbados->value                     => __('Barbados'),
            self::Belarus->value                      => __('Belarus'),
            self::Belgium->value                      => __('Belgium'),
            self::Belize->value                       => __('Belize'),
            self::Benin->value                        => __('Benin'),
            self::Bermuda->value                      => __('Bermuda'),
            self::Bhutan->value                       => __('Bhutan'),
            self::Bolivia->value                      => __('Bolivia'),
            self::BosniaAndHerzegovina->value         => __('Bosnia and Herzegovina'),
            self::Botswana->value                     => __('Botswana'),
            self::Brazil->value                       => __('Brazil'),
            self::BritishIndianOceanTerritory->value  => __('British Indian Ocean Territory'),
            self::BritishVirginIslands->value         => __('British Virgin Islands'),
            self::Brunei->value                       => __('Brunei'),
            self::Bulgaria->value                     => __('Bulgaria'),
            self::BurkinaFaso->value                  => __('Burkina Faso'),
            self::Myanmar->value                      => __('Myanmar'),
            self::Burundi->value                      => __('Burundi'),
            self::Cambodia->value                     => __('Cambodia'),
            self::Cameroon->value                     => __('Cameroon'),
            self::Canada->value                       => __('Canada'),
            self::CapeVerde->value                    => __('Cape Verde'),
            self::CaymanIslands->value                => __('Cayman Islands'),
            self::CentralAfricanRepublic->value       => __('Central African Republic'),
            self::Chad->value                         => __('Chad'),
            self::Chile->value                        => __('Chile'),
            self::China->value                        => __('China'),
            self::ChristmasIsland->value              => __('Christmas Island'),
            self::CocosIslands->value                 => __('Cocos Islands'),
            self::Colombia->value                     => __('Colombia'),
            self::Comoros->value                      => __('Comoros'),
            self::RepublicOfTheCongo->value           => __('Republic of the Congo'),
            self::DemocraticRepublicOfTheCongo->value => __('Democratic Republic of the Congo'),
            self::CookIslands->value                  => __('Cook Islands'),
            self::CostaRica->value                    => __('Costa Rica'),
            self::Croatia->value                      => __('Croatia'),
            self::Cuba->value                         => __('Cuba'),
            self::Curacao->value                      => __('Curacao'),
            self::Cyprus->value                       => __('Cyprus'),
            self::CzechRepublic->value                => __('Czech Republic'),
            self::Denmark->value                      => __('Denmark'),
            self::Djibouti->value                     => __('Djibouti'),
            self::Dominica->value                     => __('Dominica'),
            self::DominicanRepublic->value            => __('Dominican Republic'),
            self::EastTimor->value                    => __('East Timor'),
            self::Ecuador->value                      => __('Ecuador'),
            self::Egypt->value                        => __('Egypt'),
            self::ElSalvador->value                   => __('El Salvador'),
            self::EquatorialGuinea->value             => __('Equatorial Guinea'),
            self::Eritrea->value                      => __('Eritrea'),
            self::Estonia->value                      => __('Estonia'),
            self::Ethiopia->value                     => __('Ethiopia'),
            self::FalklandIslands->value              => __('Falkland Islands'),
            self::FaroeIslands->value                 => __('Faroe Islands'),
            self::Fiji->value                         => __('Fiji'),
            self::Finland->value                      => __('Finland'),
            self::France->value                       => __('France'),
            self::FrenchPolynesia->value              => __('French Polynesia'),
            self::Gabon->value                        => __('Gabon'),
            self::Gambia->value                       => __('Gambia'),
            self::Georgia->value                      => __('Georgia'),
            self::Germany->value                      => __('Germany'),
            self::Ghana->value                        => __('Ghana'),
            self::Gibraltar->value                    => __('Gibraltar'),
            self::Greece->value                       => __('Greece'),
            self::Greenland->value                    => __('Greenland'),
            self::Grenada->value                      => __('Grenada'),
            self::Guam->value                         => __('Guam'),
            self::Guatemala->value                    => __('Guatemala'),
            self::Guernsey->value                     => __('Guernsey'),
            self::Guinea->value                       => __('Guinea'),
            self::GuineaBissau->value                 => __('Guinea-Bissau'),
            self::Guyana->value                       => __('Guyana'),
            self::Haiti->value                        => __('Haiti'),
            self::Honduras->value                     => __('Honduras'),
            self::HongKong->value                     => __('Hong Kong'),
            self::Hungary->value                      => __('Hungary'),
            self::Iceland->value                      => __('Iceland'),
            self::India->value                        => __('India'),
            self::Indonesia->value                    => __('Indonesia'),
            self::Iran->value                         => __('Iran'),
            self::Iraq->value                         => __('Iraq'),
            self::Ireland->value                      => __('Ireland'),
            self::IsleOfMan->value                    => __('Isle of Man'),
            self::Israel->value                       => __('Israel'),
            self::Italy->value                        => __('Italy'),
            self::IvoryCoast->value                   => __('Ivory Coast'),
            self::Jamaica->value                      => __('Jamaica'),
            self::Japan->value                        => __('Japan'),
            self::Jersey->value                       => __('Jersey'),
            self::Jordan->value                       => __('Jordan'),
            self::Kazakhstan->value                   => __('Kazakhstan'),
            self::Kenya->value                        => __('Kenya'),
            self::Kiribati->value                     => __('Kiribati'),
            self::Kosovo->value                       => __('Kosovo'),
            self::Kuwait->value                       => __('Kuwait'),
            self::Kyrgyzstan->value                   => __('Kyrgyzstan'),
            self::Laos->value                         => __('Laos'),
            self::Latvia->value                       => __('Latvia'),
            self::Lebanon->value                      => __('Lebanon'),
            self::Lesotho->value                      => __('Lesotho'),
            self::Liberia->value                      => __('Liberia'),
            self::Libya->value                        => __('Libya'),
            self::Liechtenstein->value                => __('Liechtenstein'),
            self::Lithuania->value                    => __('Lithuania'),
            self::Luxembourg->value                   => __('Luxembourg'),
            self::Macau->value                        => __('Macau'),
            self::Macedonia->value                    => __('Macedonia'),
            self::Madagascar->value                   => __('Madagascar'),
            self::Malawi->value                       => __('Malawi'),
            self::Malaysia->value                     => __('Malaysia'),
            self::Maldives->value                     => __('Maldives'),
            self::Mali->value                         => __('Mali'),
            self::Malta->value                        => __('Malta'),
            self::MarshallIslands->value              => __('Marshall Islands'),
            self::Mauritania->value                   => __('Mauritania'),
            self::Mauritius->value                    => __('Mauritius'),
            self::Mayotte->value                      => __('Mayotte'),
            self::Mexico->value                       => __('Mexico'),
            self::Micronesia->value                   => __('Micronesia'),
            self::Moldova->value                      => __('Moldova'),
            self::Monaco->value                       => __('Monaco'),
            self::Mongolia->value                     => __('Mongolia'),
            self::Montenegro->value                   => __('Montenegro'),
            self::Montserrat->value                   => __('Montserrat'),
            self::Morocco->value                      => __('Morocco'),
            self::Mozambique->value                   => __('Mozambique'),
            self::Namibia->value                      => __('Namibia'),
            self::Nauru->value                        => __('Nauru'),
            self::Nepal->value                        => __('Nepal'),
            self::Netherlands->value                  => __('Netherlands'),
            self::NetherlandsAntilles->value          => __('Netherlands Antilles'),
            self::NewCaledonia->value                 => __('New Caledonia'),
            self::NewZealand->value                   => __('New Zealand'),
            self::Nicaragua->value                    => __('Nicaragua'),
            self::Niger->value                        => __('Niger'),
            self::Nigeria->value                      => __('Nigeria'),
            self::Niue->value                         => __('Niue'),
            self::NorthernMarianaIslands->value       => __('Northern Mariana Islands'),
            self::NorthKorea->value                   => __('North Korea'),
            self::Norway->value                       => __('Norway'),
            self::Oman->value                         => __('Oman'),
            self::Pakistan->value                     => __('Pakistan'),
            self::Palau->value                        => __('Palau'),
            self::Palestine->value                    => __('Palestine'),
            self::Panama->value                       => __('Panama'),
            self::PapuaNewGuinea->value               => __('Papua New Guinea'),
            self::Paraguay->value                     => __('Paraguay'),
            self::Peru->value                         => __('Peru'),
            self::Philippines->value                  => __('Philippines'),
            self::Pitcairn->value                     => __('Pitcairn'),
            self::Poland->value                       => __('Poland'),
            self::Portugal->value                     => __('Portugal'),
            self::PuertoRico->value                   => __('Puerto Rico'),
            self::Qatar->value                        => __('Qatar'),
            self::Reunion->value                      => __('Reunion'),
            self::Romania->value                      => __('Romania'),
            self::Russia->value                       => __('Russia'),
            self::Rwanda->value                       => __('Rwanda'),
            self::SaintBarthelemy->value              => __('Saint Barthelemy'),
            self::Samoa->value                        => __('Samoa'),
            self::SanMarino->value                    => __('San Marino'),
            self::SaoTomeAndPrincipe->value           => __('Sao Tome and Principe'),
            self::SaudiArabia->value                  => __('Saudi Arabia'),
            self::Senegal->value                      => __('Senegal'),
            self::Serbia->value                       => __('Serbia'),
            self::Seychelles->value                   => __('Seychelles'),
            self::SierraLeone->value                  => __('Sierra Leone'),
            self::Singapore->value                    => __('Singapore'),
            self::SintMaarten->value                  => __('Sint Maarten'),
            self::Slovakia->value                     => __('Slovakia'),
            self::Slovenia->value                     => __('Slovenia'),
            self::SolomonIslands->value               => __('Solomon Islands'),
            self::Somalia->value                      => __('Somalia'),
            self::SouthAfrica->value                  => __('South Africa'),
            self::SouthKorea->value                   => __('South Korea'),
            self::SouthSudan->value                   => __('South Sudan'),
            self::Spain->value                        => __('Spain'),
            self::SriLanka->value                     => __('Sri Lanka'),
            self::SaintHelena->value                  => __('Saint Helena'),
            self::SaintKittsAndNevis->value           => __('Saint Kitts and Nevis'),
            self::SaintLucia->value                   => __('Saint Lucia'),
            self::SaintMartin->value                  => __('Saint Martin'),
            self::SaintPierreAndMiquelon->value       => __('Saint Pierre and Miquelon'),
            self::SaintVincentAndTheGrenadines->value => __('Saint Vincent and the Grenadines'),
            self::Sudan->value                        => __('Sudan'),
            self::Suriname->value                     => __('Suriname'),
            self::SvalbardAndJanMayen->value          => __('Svalbard and Jan Mayen'),
            self::Swaziland->value                    => __('Swaziland'),
            self::Sweden->value                       => __('Sweden'),
            self::Switzerland->value                  => __('Switzerland'),
            self::Syria->value                        => __('Syria'),
            self::Taiwan->value                       => __('Taiwan'),
            self::Tajikistan->value                   => __('Tajikistan'),
            self::Tanzania->value                     => __('Tanzania'),
            self::Thailand->value                     => __('Thailand'),
            self::Togo->value                         => __('Togo'),
            self::Tokelau->value                      => __('Tokelau'),
            self::Tonga->value                        => __('Tonga'),
            self::TrinidadAndTobago->value            => __('Trinidad and Tobago'),
            self::Tunisia->value                      => __('Tunisia'),
            self::Turkey->value                       => __('Turkey'),
            self::Turkmenistan->value                 => __('Turkmenistan'),
            self::TurksAndCaicosIslands->value        => __('Turks and Caicos Islands'),
            self::Tuvalu->value                       => __('Tuvalu'),
            self::UnitedArabEmirates->value           => __('United Arab Emirates'),
            self::Uganda->value                       => __('Uganda'),
            self::UnitedKingdom->value                => __('United Kingdom'),
            self::Ukraine->value                      => __('Ukraine'),
            self::Uruguay->value                      => __('Uruguay'),
            self::UnitedStates->value                 => __('United States'),
            self::Uzbekistan->value                   => __('Uzbekistan'),
            self::Vanuatu->value                      => __('Vanuatu'),
            self::Vatican->value                      => __('Vatican'),
            self::Venezuela->value                    => __('Venezuela'),
            self::Vietnam->value                      => __('Vietnam'),
            self::USVirginIslands->value              => __('U.S. Virgin Islands'),
            self::WallisAndFutuna->value              => __('Wallis and Futuna'),
            self::WesternSahara->value                => __('Western Sahara'),
            self::Yemen->value                        => __('Yemen'),
            self::Zambia->value                       => __('Zambia'),
            self::Zimbabwe->value                     => __('Zimbabwe'),
        ];
    }


    public static function countryCodes(): array
    {
        return [
            self::Afghanistan->value                  => '93',
            self::Albania->value                      => '355',
            self::Algeria->value                      => '213',
            self::AmericanSamoa->value                => '1-684',
            self::Andorra->value                      => '376',
            self::Angola->value                       => '244',
            self::Anguilla->value                     => '1-264',
            self::Antarctica->value                   => '672',
            self::AntiguaAndBarbuda->value            => '1-268',
            self::Argentina->value                    => '54',
            self::Armenia->value                      => '374',
            self::Aruba->value                        => '297',
            self::Australia->value                    => '61',
            self::Austria->value                      => '43',
            self::Azerbaijan->value                   => '994',
            self::Bahamas->value                      => '1-242',
            self::Bahrain->value                      => '973',
            self::Bangladesh->value                   => '880',
            self::Barbados->value                     => '1-246',
            self::Belarus->value                      => '375',
            self::Belgium->value                      => '32',
            self::Belize->value                       => '501',
            self::Benin->value                        => '229',
            self::Bermuda->value                      => '1-441',
            self::Bhutan->value                       => '975',
            self::Bolivia->value                      => '591',
            self::BosniaAndHerzegovina->value         => '387',
            self::Botswana->value                     => '267',
            self::Brazil->value                       => '55',
            self::BritishIndianOceanTerritory->value  => '246',
            self::BritishVirginIslands->value         => '1-284',
            self::Brunei->value                       => '673',
            self::Bulgaria->value                     => '359',
            self::BurkinaFaso->value                  => '226',
            self::Myanmar->value                      => '95',
            self::Burundi->value                      => '257',
            self::Cambodia->value                     => '855',
            self::Cameroon->value                     => '237',
            self::Canada->value                       => '1',
            self::CapeVerde->value                    => '238',
            self::CaymanIslands->value                => '1-345',
            self::CentralAfricanRepublic->value       => '236',
            self::Chad->value                         => '235',
            self::Chile->value                        => '56',
            self::China->value                        => '86',
            self::ChristmasIsland->value              => '61',
            self::CocosIslands->value                 => '61',
            self::Colombia->value                     => '57',
            self::Comoros->value                      => '269',
            self::RepublicOfTheCongo->value           => '242',
            self::DemocraticRepublicOfTheCongo->value => '243',
            self::CookIslands->value                  => '682',
            self::CostaRica->value                    => '506',
            self::Croatia->value                      => '385',
            self::Cuba->value                         => '53',
            self::Curacao->value                      => '599',
            self::Cyprus->value                       => '357',
            self::CzechRepublic->value                => '420',
            self::Denmark->value                      => '45',
            self::Djibouti->value                     => '253',
            self::Dominica->value                     => '1-767',
            self::DominicanRepublic->value            => '1-809, 1-829, 1-849',
            self::EastTimor->value                    => '670',
            self::Ecuador->value                      => '593',
            self::Egypt->value                        => '20',
            self::ElSalvador->value                   => '503',
            self::EquatorialGuinea->value             => '240',
            self::Eritrea->value                      => '291',
            self::Estonia->value                      => '372',
            self::Ethiopia->value                     => '251',
            self::FalklandIslands->value              => '500',
            self::FaroeIslands->value                 => '298',
            self::Fiji->value                         => '679',
            self::Finland->value                      => '358',
            self::France->value                       => '33',
            self::FrenchPolynesia->value              => '689',
            self::Gabon->value                        => '241',
            self::Gambia->value                       => '220',
            self::Georgia->value                      => '995',
            self::Germany->value                      => '49',
            self::Ghana->value                        => '233',
            self::Gibraltar->value                    => '350',
            self::Greece->value                       => '30',
            self::Greenland->value                    => '299',
            self::Grenada->value                      => '1-473',
            self::Guam->value                         => '1-671',
            self::Guatemala->value                    => '502',
            self::Guernsey->value                     => '44-1481',
            self::Guinea->value                       => '224',
            self::GuineaBissau->value                 => '245',
            self::Guyana->value                       => '592',
            self::Haiti->value                        => '509',
            self::Honduras->value                     => '504',
            self::HongKong->value                     => '852',
            self::Hungary->value                      => '36',
            self::Iceland->value                      => '354',
            self::India->value                        => '91',
            self::Indonesia->value                    => '62',
            self::Iran->value                         => '98',
            self::Iraq->value                         => '964',
            self::Ireland->value                      => '353',
            self::IsleOfMan->value                    => '44-1624',
            self::Israel->value                       => '972',
            self::Italy->value                        => '39',
            self::IvoryCoast->value                   => '225',
            self::Jamaica->value                      => '1-876',
            self::Japan->value                        => '81',
            self::Jersey->value                       => '44-1534',
            self::Jordan->value                       => '962',
            self::Kazakhstan->value                   => '7',
            self::Kenya->value                        => '254',
            self::Kiribati->value                     => '686',
            self::Kosovo->value                       => '383',
            self::Kuwait->value                       => '965',
            self::Kyrgyzstan->value                   => '996',
            self::Laos->value                         => '856',
            self::Latvia->value                       => '371',
            self::Lebanon->value                      => '961',
            self::Lesotho->value                      => '266',
            self::Liberia->value                      => '231',
            self::Libya->value                        => '218',
            self::Liechtenstein->value                => '423',
            self::Lithuania->value                    => '370',
            self::Luxembourg->value                   => '352',
            self::Macau->value                        => '853',
            self::Macedonia->value                    => '389',
            self::Madagascar->value                   => '261',
            self::Malawi->value                       => '265',
            self::Malaysia->value                     => '60',
            self::Maldives->value                     => '960',
            self::Mali->value                         => '223',
            self::Malta->value                        => '356',
            self::MarshallIslands->value              => '692',
            self::Mauritania->value                   => '222',
            self::Mauritius->value                    => '230',
            self::Mayotte->value                      => '262',
            self::Mexico->value                       => '52',
            self::Micronesia->value                   => '691',
            self::Moldova->value                      => '373',
            self::Monaco->value                       => '377',
            self::Mongolia->value                     => '976',
            self::Montenegro->value                   => '382',
            self::Montserrat->value                   => '1-664',
            self::Morocco->value                      => '212',
            self::Mozambique->value                   => '258',
            self::Namibia->value                      => '264',
            self::Nauru->value                        => '674',
            self::Nepal->value                        => '977',
            self::Netherlands->value                  => '31',
            self::NetherlandsAntilles->value          => '599',
            self::NewCaledonia->value                 => '687',
            self::NewZealand->value                   => '64',
            self::Nicaragua->value                    => '505',
            self::Niger->value                        => '227',
            self::Nigeria->value                      => '234',
            self::Niue->value                         => '683',
            self::NorthernMarianaIslands->value       => '1-670',
            self::NorthKorea->value                   => '850',
            self::Norway->value                       => '47',
            self::Oman->value                         => '968',
            self::Pakistan->value                     => '92',
            self::Palau->value                        => '680',
            self::Palestine->value                    => '970',
            self::Panama->value                       => '507',
            self::PapuaNewGuinea->value               => '675',
            self::Paraguay->value                     => '595',
            self::Peru->value                         => '51',
            self::Philippines->value                  => '63',
            self::Pitcairn->value                     => '64',
            self::Poland->value                       => '48',
            self::Portugal->value                     => '351',
            self::PuertoRico->value                   => '1-787, 1-939',
            self::Qatar->value                        => '974',
            self::Reunion->value                      => '262',
            self::Romania->value                      => '40',
            self::Russia->value                       => '7',
            self::Rwanda->value                       => '250',
            self::SaintBarthelemy->value              => '590',
            self::Samoa->value                        => '685',
            self::SanMarino->value                    => '378',
            self::SaoTomeAndPrincipe->value           => '239',
            self::SaudiArabia->value                  => '966',
            self::Senegal->value                      => '221',
            self::Serbia->value                       => '381',
            self::Seychelles->value                   => '248',
            self::SierraLeone->value                  => '232',
            self::Singapore->value                    => '65',
            self::SintMaarten->value                  => '1-721',
            self::Slovakia->value                     => '421',
            self::Slovenia->value                     => '386',
            self::SolomonIslands->value               => '677',
            self::Somalia->value                      => '252',
            self::SouthAfrica->value                  => '27',
            self::SouthKorea->value                   => '82',
            self::SouthSudan->value                   => '211',
            self::Spain->value                        => '34',
            self::SriLanka->value                     => '94',
            self::SaintHelena->value                  => '290',
            self::SaintKittsAndNevis->value           => '1-869',
            self::SaintLucia->value                   => '1-758',
            self::SaintMartin->value                  => '590',
            self::SaintPierreAndMiquelon->value       => '508',
            self::SaintVincentAndTheGrenadines->value => '1-784',
            self::Sudan->value                        => '249',
            self::Suriname->value                     => '597',
            self::SvalbardAndJanMayen->value          => '47',
            self::Swaziland->value                    => '268',
            self::Sweden->value                       => '46',
            self::Switzerland->value                  => '41',
            self::Syria->value                        => '963',
            self::Taiwan->value                       => '886',
            self::Tajikistan->value                   => '992',
            self::Tanzania->value                     => '255',
            self::Thailand->value                     => '66',
            self::Togo->value                         => '228',
            self::Tokelau->value                      => '690',
            self::Tonga->value                        => '676',
            self::TrinidadAndTobago->value            => '1-868',
            self::Tunisia->value                      => '216',
            self::Turkey->value                       => '90',
            self::Turkmenistan->value                 => '993',
            self::TurksAndCaicosIslands->value        => '1-649',
            self::Tuvalu->value                       => '688',
            self::UnitedArabEmirates->value           => '971',
            self::Uganda->value                       => '256',
            self::UnitedKingdom->value                => '44',
            self::Ukraine->value                      => '380',
            self::Uruguay->value                      => '598',
            self::UnitedStates->value                 => '1',
            self::Uzbekistan->value                   => '998',
            self::Vanuatu->value                      => '678',
            self::Vatican->value                      => '379',
            self::Venezuela->value                    => '58',
            self::Vietnam->value                      => '84',
            self::USVirginIslands->value              => '1-340',
            self::WallisAndFutuna->value              => '681',
            self::WesternSahara->value                => '212',
            self::Yemen->value                        => '967',
            self::Zambia->value                       => '260',
            self::Zimbabwe->value                     => '263',
        ];
    }

    public function getLabel(): string
    {
        return self::labels()[$this->value];
    }

    public function getCountryCode(): string
    {
        return self::countryCodes()[$this->value];
    }

    // String of country codes separated by coma for validation rule
    public static function getCountryCodesString(): string
    {
        return implode(',', array_values(self::countryCodes()));
    }
}
